export { DepartmentsPage } from './pages/departments-page'
export { useDepartments } from './hooks/use-departments'
export { departmentsApi } from './api/departments-api'
export { mockDepartments } from './data/mock-departments'
export type { Department } from './types'
