export type { Insight, InsightSeverity, InsightModule } from './types'
export { SEVERITY_RANK } from './types'
export { InsightsPanel } from './components/insights-panel'
export { useInsights } from './hooks/use-insights'
export { deriveInventoryInsights } from './lib/derive-inventory'
export { deriveMaintenanceInsights } from './lib/derive-maintenance'
export { deriveProcurementInsights } from './lib/derive-procurement'
export { deriveAssetInsights } from './lib/derive-assets'
export { deriveFleetInsights } from './lib/derive-fleet'
